ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE devices ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE configs ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE configs ALTER COLUMN updated_at TYPE TIMESTAMP;
ALTER TABLE logs ALTER COLUMN Created_At TYPE TIMESTAMP;
ALTER TABLE events ALTER COLUMN scheduled_at TYPE TIMESTAMP;
ALTER TABLE events ALTER COLUMN created_at TYPE TIMESTAMP;
ALTER TABLE events ALTER COLUMN deployed_at TYPE TIMESTAMP;
