ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE devices ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE configs ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE configs ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE logs ALTER COLUMN Created_At TYPE TIMESTAMPTZ;
ALTER TABLE events ALTER COLUMN scheduled_at TYPE TIMESTAMPTZ;
ALTER TABLE events ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE events ALTER COLUMN deployed_at TYPE TIMESTAMPTZ;
